---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Create EC2
    ec2_instance:
      key_name: "{{ key_name }}"
      security_group: "{{ sec_group }}"
      image_id: "{{ image }}"
      instance_type: "{{ instance_type }}"
      region: "{{ region }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_role: "{{ iam_role }}"
      wait: true
      volumes:
        - device_name: /dev/sda1
          ebs:
            volume_type: gp2
            volume_size: "{{ root_volume_size }}"
            delete_on_termination: true
            encrypted: true
      name: "{{ instance_name }}"
      tags:
        created_by: "{{ your_name }}"
      user_data: |
        #!/bin/bash
        yum update -y
        yum install httpd -y
        service httpd start
        chkconfig httpd on
        echo "<html><body><h1>Hello JJTech Team</h1></body></html>" > /var/www/html/index.html
